Repository appsignal/test-setups, pull requests merged in 2021-01, with the labels that each got.

#5 Add diagnose
  README.md
  Rakefile
  appsignal.env
  elixir/phoenix-example/commands/diagnose.sh
  ruby/rails-postgres/commands/diagnose.sh
  support/templates/README.md.erb
  support/templates/skeleton/commands/diagnose.sh
Labels: enhancement

#4 Add express postgrest test app
  .gitignore
  README.md
  Rakefile
  nodejs/express-postgres/Dockerfile
  nodejs/express-postgres/README.md
  nodejs/express-postgres/app/app.js
  nodejs/express-postgres/app/appsignal.js
  nodejs/express-postgres/app/package.json
  nodejs/express-postgres/app/views/index.pug
  nodejs/express-postgres/app/views/new.pug
  nodejs/express-postgres/commands/boot.sh
  nodejs/express-postgres/docker-compose.yml
  nodejs/express-postgres/postgres.env
  support/templates/skeleton/commands/boot.sh
Labels: enhancement

#6 Add Shoryuken example app
  ruby/shoryuken/Dockerfile
  ruby/shoryuken/README.md
  ruby/shoryuken/app/Gemfile
  ruby/shoryuken/app/Gemfile.lock
  ruby/shoryuken/app/app.rb
  ruby/shoryuken/app/boot.rb
  ruby/shoryuken/app/config/appsignal.yml
  ruby/shoryuken/app/shoryuken.yml
  ruby/shoryuken/app/workers.rb
  ruby/shoryuken/app/workers/batched_worker.rb
  ruby/shoryuken/app/workers/single_worker.rb
  ruby/shoryuken/commands/boot.sh
  ruby/shoryuken/commands/console.sh
  ruby/shoryuken/commands/diagnose.sh
  ruby/shoryuken/docker-compose.yml
  ruby/shoryuken/shoryuken.env
Labels: chore

#7 Wait for child process to gracefully exit
  Rakefile
Labels: chore, dev happiness

#8 Update rails-postgres example to use PostgreSQL
  ruby/rails-postgres/app/Gemfile
  ruby/rails-postgres/app/Gemfile.lock
  ruby/rails-postgres/app/config/database.yml
  ruby/rails-postgres/app/db/schema.rb
  ruby/rails-postgres/commands/boot.sh
Labels: chore

#11 Add Ruby single task app
  ruby/single-task/Dockerfile
  ruby/single-task/README.md
  ruby/single-task/app/Gemfile
  ruby/single-task/app/Gemfile.lock
  ruby/single-task/app/app.rb
  ruby/single-task/commands/boot.sh
  ruby/single-task/commands/console.sh
  ruby/single-task/commands/diagnose.sh
  ruby/single-task/docker-compose.yml
Labels: chore

#13 Make default app port 4001
  README.md
  Rakefile
  elixir/alpine-release/docker-compose.yml
  elixir/phoenix-example/docker-compose.yml
  nodejs/express-postgres/docker-compose.yml
  ruby/rails-postgres/commands/boot.sh
  ruby/rails-postgres/docker-compose.yml
  ruby/shoryuken/app/Gemfile.lock
  ruby/shoryuken/docker-compose.yml
  ruby/single-task/docker-compose.yml
  support/templates/README.md.erb
  support/templates/skeleton/docker-compose.yml.erb
Labels: chore

#15 Use docker compose to build images
  Rakefile
  elixir/alpine-release/docker-compose.yml
  elixir/phoenix-example/docker-compose.yml
  nodejs/express-postgres/docker-compose.yml
  ruby/rails-postgres/docker-compose.yml
  ruby/shoryuken/docker-compose.yml
  ruby/single-task/docker-compose.yml
  support/templates/skeleton/docker-compose.yml.erb
Labels: enhancement

#14 Add create-react-app example app
  .gitignore
  Rakefile
  javascript/react/Dockerfile
  javascript/react/README.md
  javascript/react/app/.gitignore
  javascript/react/app/README.md
  javascript/react/app/package.json
  javascript/react/app/public/favicon.ico
  javascript/react/app/public/index.html
  javascript/react/app/public/logo192.png
  javascript/react/app/public/logo512.png
  javascript/react/app/public/manifest.json
  javascript/react/app/public/robots.txt
  javascript/react/app/src/App.css
  javascript/react/app/src/App.js
  javascript/react/app/src/App.test.js
  javascript/react/app/src/Appsignal.js
  javascript/react/app/src/index.css
  javascript/react/app/src/index.js
  javascript/react/app/src/logo.svg
  javascript/react/app/src/reportWebVitals.js
  javascript/react/app/src/setupTests.js
  javascript/react/commands/boot.sh
  javascript/react/docker-compose.yml
Labels: chore

#16 Add JavaScript webpack test app
  javascript/webpack/Dockerfile
  javascript/webpack/README.md
  javascript/webpack/app.env
  javascript/webpack/app/.gitignore
  javascript/webpack/app/package.json
  javascript/webpack/app/src/Appsignal.js
  javascript/webpack/app/src/index.html
  javascript/webpack/app/src/index.js
  javascript/webpack/app/webpack.config.js
  javascript/webpack/commands/boot.sh
  javascript/webpack/commands/console.sh
  javascript/webpack/docker-compose.yml
Labels: chore
