Repository appsignal/test-setups, pull requests merged in 2022-01, with the labels that each got.

#44 Update express-postgres app format
  nodejs/express-apollo/app/appsignal.js
  nodejs/express-postgres/Dockerfile
  nodejs/express-postgres/app/app.js
  nodejs/express-postgres/commands/prepare
  nodejs/express-postgres/commands/run
Labels: chore

#45 Update react app
  javascript/react/app/package.json
  javascript/react/app/src/App.js
  javascript/react/commands/run
Labels: chore

#46 Track errors in React using ErrorBoundary
  javascript/react/app/src/App.js
Labels: chore

#48 Downgrade rails-sidekiq to Node 14.x
  ruby/rails-sidekiq/Dockerfile
Labels: chore

#52 Update `alpine-release` Elixir to 1.13
  elixir/alpine-release/Dockerfile
  elixir/alpine-release/app/assets/package-lock.json
  elixir/alpine-release/app/assets/package.json
  elixir/alpine-release/app/mix.exs
Labels: bug

#51 Add Ember test setup
  .semaphore/semaphore.yml
  javascript/ember/README.md
  javascript/ember/app/.editorconfig
  javascript/ember/app/.ember-cli
  javascript/ember/app/.eslintignore
  javascript/ember/app/.eslintrc.js
  javascript/ember/app/.gitignore
  javascript/ember/app/.prettierignore
  javascript/ember/app/.prettierrc.js
  javascript/ember/app/.template-lintrc.js
  javascript/ember/app/.watchmanconfig
  javascript/ember/app/app/app.js
  javascript/ember/app/app/components/.gitkeep
  javascript/ember/app/app/controllers/.gitkeep
  javascript/ember/app/app/helpers/.gitkeep
  javascript/ember/app/app/index.html
  javascript/ember/app/app/models/.gitkeep
  javascript/ember/app/app/router.js
  javascript/ember/app/app/routes/.gitkeep
  javascript/ember/app/app/routes/error.js
  javascript/ember/app/app/styles/app.css
  javascript/ember/app/app/templates/application.hbs
  javascript/ember/app/app/templates/error.hbs
  javascript/ember/app/config/ember-cli-update.json
  javascript/ember/app/config/environment.js
  javascript/ember/app/config/optional-features.json
  javascript/ember/app/config/targets.js
  javascript/ember/app/ember-cli-build.js
  javascript/ember/app/package.json
  javascript/ember/app/public/robots.txt
  javascript/ember/app/testem.js
  javascript/ember/app/tests/helpers/.gitkeep
  javascript/ember/app/tests/index.html
  javascript/ember/app/tests/integration/.gitkeep
  javascript/ember/app/tests/test-helper.js
  javascript/ember/app/tests/unit/.gitkeep
  javascript/ember/app/tests/unit/routes/error-test.js
  javascript/ember/commands/run
  javascript/ember/docker-compose.yml
Labels: chore

#53 Build only needed Javascript packages
  javascript/ember/commands/run
  javascript/react/commands/run
  javascript/typescript-angular/commands/run
  javascript/vanilla/commands/run
  javascript/vue-2/commands/run.sh
  javascript/vue-3/commands/run.sh
  javascript/webpack/commands/run
Labels: dev happiness

#49 Add Node.js express-redis test application
  .semaphore/semaphore.yml
  appsignal.env
  nodejs/express-redis/Dockerfile
  nodejs/express-redis/README.md
  nodejs/express-redis/app/app.js
  nodejs/express-redis/app/appsignal.js
  nodejs/express-redis/app/express.js
  nodejs/express-redis/app/package.json
  nodejs/express-redis/app/processmon.toml
  nodejs/express-redis/app/views/index.pug
  nodejs/express-redis/app/views/new.pug
  nodejs/express-redis/commands/run
  nodejs/express-redis/docker-compose.yml
Labels: enhancement
