Repository appsignal/test-setups, pull requests merged in 2023-03, with the labels that each got.

#94 Add Python test app to CI
  .semaphore/semaphore.yml
  python/django4-celery/app/appsignal_python_opentelemetry/settings.py
  python/django4-celery/app/appsignal_python_opentelemetry/views.py
  support/server-tests/spec/backend_spec.rb
Labels: chore

#95 Add logging backend to Phoenix app
  elixir/phoenix-example/app/config/runtime.exs
Labels: chore

#97 Fix Elixir resets in integrations Rake commands
  Rakefile
Labels: bug

#100 Use sparse crates.io protocol in processmon build
  support/processmon/Dockerfile
  support/processmon/build.sh
Labels: chore

#102 Add Golang setups to CI
  .semaphore/semaphore.yml
  go/beego/app/main.go
  go/beego/docker-compose.yml
  go/go-gin-mysql/app/main.go
  go/go-gin-mysql/docker-compose.yml
  go/gorilla-mux-mysql-redis-mongo/app/main.go
  go/gorilla-mux-mysql-redis-mongo/docker-compose.yml
Labels: chore

#103 Add Nestjs + Prisma v3 setup
  .semaphore/semaphore.yml
  nodejs/v3/nestjs-prisma/Dockerfile
  nodejs/v3/nestjs-prisma/app/.eslintrc.js
  nodejs/v3/nestjs-prisma/app/.gitignore
  nodejs/v3/nestjs-prisma/app/.prettierrc
  nodejs/v3/nestjs-prisma/app/README.md
  nodejs/v3/nestjs-prisma/app/appsignal.cjs
  nodejs/v3/nestjs-prisma/app/nest-cli.json
  nodejs/v3/nestjs-prisma/app/package.json
  nodejs/v3/nestjs-prisma/app/prisma/migrations/20221121113710_init/migration.sql
  nodejs/v3/nestjs-prisma/app/prisma/migrations/migration_lock.toml
  nodejs/v3/nestjs-prisma/app/prisma/schema.prisma
  nodejs/v3/nestjs-prisma/app/processmon.toml
  nodejs/v3/nestjs-prisma/app/src/app.controller.spec.ts
  nodejs/v3/nestjs-prisma/app/src/app.controller.ts
  nodejs/v3/nestjs-prisma/app/src/app.module.ts
  nodejs/v3/nestjs-prisma/app/src/app.service.ts
  nodejs/v3/nestjs-prisma/app/src/main.ts
  nodejs/v3/nestjs-prisma/app/src/post.service.ts
  nodejs/v3/nestjs-prisma/app/src/prisma.service.ts
  nodejs/v3/nestjs-prisma/app/src/user.service.ts
  nodejs/v3/nestjs-prisma/app/test/app.e2e-spec.ts
  nodejs/v3/nestjs-prisma/app/test/jest-e2e.json
  nodejs/v3/nestjs-prisma/app/tsconfig.build.json
  nodejs/v3/nestjs-prisma/app/tsconfig.json
  nodejs/v3/nestjs-prisma/commands/run
  nodejs/v3/nestjs-prisma/docker-compose.yml
Labels: chore, dev happiness

#105 Remove API key attribute from Node apps
  nodejs/v3/express-apollo/app/src/appsignal.cjs
  nodejs/v3/express-postgres/app/src/appsignal.cjs
  nodejs/v3/express-yoga/app/src/appsignal.cjs
  nodejs/v3/koa-mongo/app/src/appsignal.cjs
  nodejs/v3/koa-mysql/app/src/appsignal.cjs
  nodejs/v3/nestjs-prisma/app/appsignal.cjs
  nodejs/v3/restify/app/src/appsignal.cjs
Labels: chore
