Repository appsignal/test-setups, pull requests merged in 2023-11, with the labels that each got.

#160 Add less to almost all test apps
  Rakefile
  elixir/alpine-release/Dockerfile
  elixir/phoenix-example/Dockerfile
  elixir/plug-oban/Dockerfile
  elixir/plug/Dockerfile
  elixir/single-task/Dockerfile
  go/beego/Dockerfile
  nodejs/v3/express-apollo/Dockerfile
  nodejs/v3/express-mongoose/Dockerfile
  nodejs/v3/express-postgres/Dockerfile
  nodejs/v3/express-redis/Dockerfile
  nodejs/v3/express-yoga/Dockerfile
  nodejs/v3/fastify/Dockerfile
  nodejs/v3/koa-mongo/Dockerfile
  nodejs/v3/koa-mysql/Dockerfile
  nodejs/v3/nestjs-prisma/Dockerfile
  nodejs/v3/nestjs/Dockerfile
  nodejs/v3/nextjs-noappdir/Dockerfile
  nodejs/v3/nextjs/Dockerfile
  nodejs/v3/remix/Dockerfile
  nodejs/v3/restify/Dockerfile
  python/django4-celery/Dockerfile
  python/fastapi/Dockerfile
  python/flask/Dockerfile
  python/starlette/Dockerfile
  ruby/hanami2-postgres/Dockerfile
  ruby/jruby-rails6/Dockerfile
  ruby/jruby-single-task/Dockerfile
  ruby/linux-arm/Dockerfile
  ruby/padrino/Dockerfile
  ruby/rails6-mongo/Dockerfile
  ruby/rails6-mysql/Dockerfile
  ruby/rails6-sequel/Dockerfile
  ruby/rails6-shakapacker/Dockerfile
  ruby/rails6-shoryuken/Dockerfile
  ruby/rails7-delayed-job/Dockerfile
  ruby/rails7-goodjob/Dockerfile
  ruby/rails7-postgres/Dockerfile
  ruby/rails7-sequel/Dockerfile
  ruby/rails7-sequel/app/Gemfile.lock
  ruby/rails7-sidekiq/Dockerfile
  ruby/shoryuken/Dockerfile
  ruby/sinatra-gvltools/Dockerfile
  ruby/sinatra-puma/Dockerfile
  ruby/sinatra/Dockerfile
  ruby/single-task/Dockerfile
  ruby/webmachine/Dockerfile
Labels: dev happiness

#161 Vector + MongoDB test setup
  ruby/rails7-postgres/.gitignore
  ruby/rails7-postgres/README.md
  ruby/rails7-postgres/docker-compose.yml
  ruby/rails7-postgres/hooks/before_build
  ruby/rails7-postgres/vector/vector.toml
  vector/mongodb/app/Dockerfile
  vector/mongodb/app/app.rb
  vector/mongodb/commands/.gitkeep
  vector/mongodb/docker-compose.yml
  vector/mongodb/mongo-entrypoint.sh
  vector/mongodb/vector/vector.toml
Labels: feature

#162 Add nested errors endpoint
  python/flask/app/app.py
Labels: chore

#163 Add `Ecto.Multi` transactions endpoint
  elixir/phoenix-example/app/lib/appsignal_phoenix_example_web/controllers/page_controller.ex
  elixir/phoenix-example/app/lib/appsignal_phoenix_example_web/router.ex
  elixir/phoenix-example/app/lib/appsignal_phoenix_example_web/templates/page/index.html.eex
Labels: chore

#164 Improve Shoryuken app jobs
  ruby/rails6-shoryuken/app/Gemfile.lock
  ruby/rails6-shoryuken/app/app/controllers/tests_controller.rb
  ruby/rails6-shoryuken/app/app/jobs/error_job.rb
  ruby/rails6-shoryuken/app/app/jobs/performance_job.rb
  ruby/rails6-shoryuken/app/app/views/tests/index.html.erb
  ruby/rails6-shoryuken/app/app/views/tests/job.html.erb
  ruby/rails6-shoryuken/app/config/routes.rb
  ruby/rails6-shoryuken/app/processmon.toml
  ruby/rails6-shoryuken/commands/run
Labels: chore

#165 Remove (unintentional?) WSGI instrumentation
  python/django4-celery/app/appsignal_python_opentelemetry/wsgi.py
Labels: chore

#168 Remove duplicate app names from Node.js configs
  nodejs/v3/express-apollo/app/src/appsignal.cjs
  nodejs/v3/express-mongoose/app/src/appsignal.cjs
  nodejs/v3/express-postgres/app/src/appsignal.cjs
  nodejs/v3/express-redis/app/src/appsignal.cjs
  nodejs/v3/express-yoga/app/src/appsignal.cjs
  nodejs/v3/fastify/app/src/appsignal.cjs
  nodejs/v3/koa-mongo/app/src/appsignal.cjs
  nodejs/v3/koa-mysql/app/src/appsignal.cjs
  nodejs/v3/nestjs/app/src/appsignal.cjs
  nodejs/v3/nextjs/app/appsignal.cjs
  nodejs/v3/remix/app/appsignal.cjs
  nodejs/v3/restify/app/src/appsignal.cjs
Labels: chore

#169 Add Winston custom log levels example
  nodejs/v3/express-redis/app/package-lock.json
  nodejs/v3/express-redis/app/src/app.ts
Labels: chore
