Repository appsignal/test-setups, pull requests merged in 2024-07, with the labels that each got.

#216 Update webmachine apps
  .semaphore/semaphore.yml
  ruby/webmachine/README.md
  ruby/webmachine1/Dockerfile
  ruby/webmachine1/app/Gemfile
  ruby/webmachine1/app/Gemfile.lock
  ruby/webmachine1/app/app.rb
  ruby/webmachine1/app/config.ru
  ruby/webmachine1/app/processmon.toml
  ruby/webmachine1/commands/diagnose
  ruby/webmachine1/commands/run
  ruby/webmachine1/docker-compose.yml
  ruby/webmachine2/Dockerfile
  ruby/webmachine2/app/Gemfile
  ruby/webmachine2/app/Gemfile.lock
  ruby/webmachine2/app/app.rb
  ruby/webmachine2/app/config.ru
  ruby/webmachine2/app/processmon.toml
  ruby/webmachine2/commands/diagnose
  ruby/webmachine2/commands/run
  ruby/webmachine2/docker-compose.yml
Labels: chore

#217 Always switch branches on integrations clone
  Rakefile
Labels: enhancement

#218 Remove old agent artifacts on integrations clone
  Rakefile
Labels: bug

#219 Avoid boot loop on NestJS + Prisma build
  nodejs/nestjs-prisma/app/processmon.toml
Labels: chore

#220 Add Prisma migration
  nodejs/nestjs-prisma/app/prisma/migrations/20240704123353_init/migration.sql
Labels: chore

#222 Add multiple errors endpoint
  ruby/sinatra-puma/app/app.rb
Labels: chore

#223 Clone Ruby integration's main branch
  Rakefile
Labels: chore

#224 Next js production backend source maps
  nodejs/nextjs-13-app/app/next.config.js
  nodejs/nextjs-13-app/app/package-lock.json
  nodejs/nextjs-13-app/app/package.json
  nodejs/nextjs-13-pages/app/next.config.js
  nodejs/nextjs-13-pages/app/package-lock.json
  nodejs/nextjs-13-pages/app/package.json
  nodejs/nextjs-14-app/app/next.config.mjs
  nodejs/nextjs-14-app/app/package-lock.json
  nodejs/nextjs-14-app/app/package.json
  nodejs/nextjs-14-pages/app/next.config.mjs
  nodejs/nextjs-14-pages/app/package-lock.json
  nodejs/nextjs-14-pages/app/package.json
Labels: chore
