Repository appsignal/test-setups, pull requests merged in 2024-06, with the labels that each got.

#202 Add Express RabbitMQ app
  nodejs/express-rabbitmq/Dockerfile
  nodejs/express-rabbitmq/app/.gitignore
  nodejs/express-rabbitmq/app/package-lock.json
  nodejs/express-rabbitmq/app/package.json
  nodejs/express-rabbitmq/app/processmon.toml
  nodejs/express-rabbitmq/app/src/app.ts
  nodejs/express-rabbitmq/app/src/appsignal.cjs
  nodejs/express-rabbitmq/app/tsconfig.json
  nodejs/express-rabbitmq/commands/demo
  nodejs/express-rabbitmq/commands/run
  nodejs/express-rabbitmq/docker-compose.yml
Labels: enhancement

#211 Add Express + BullMQ test setup
  .gitignore
  .semaphore/semaphore.yml
  nodejs/express-bullmq/Dockerfile
  nodejs/express-bullmq/app/.gitignore
  nodejs/express-bullmq/app/package-lock.json
  nodejs/express-bullmq/app/package.json
  nodejs/express-bullmq/app/processmon.toml
  nodejs/express-bullmq/app/src/app.ts
  nodejs/express-bullmq/app/src/appsignal.cjs
  nodejs/express-bullmq/app/src/worker.ts
  nodejs/express-bullmq/app/tsconfig.json
  nodejs/express-bullmq/commands/demo
  nodejs/express-bullmq/commands/run
  nodejs/express-bullmq/docker-compose.yml
Labels: chore

#214 Add Ruby Rack test app
  .semaphore/semaphore.yml
  ruby/rack/Dockerfile
  ruby/rack/app/Gemfile
  ruby/rack/app/Gemfile.lock
  ruby/rack/app/app.rb
  ruby/rack/app/config.ru
  ruby/rack/app/processmon.toml
  ruby/rack/commands/run
  ruby/rack/docker-compose.yml
Labels: chore

#215 Add Ruby grape app
  .semaphore/semaphore.yml
  ruby/grape/Dockerfile
  ruby/grape/app/Gemfile
  ruby/grape/app/Gemfile.lock
  ruby/grape/app/api.rb
  ruby/grape/app/config.ru
  ruby/grape/app/processmon.toml
  ruby/grape/commands/run
  ruby/grape/docker-compose.yml
Labels: chore

#212 Flask-Pika app
  python/flask-pika/Dockerfile
  python/flask-pika/app/.gitignore
  python/flask-pika/app/__appsignal__.py
  python/flask-pika/app/app.py
  python/flask-pika/app/pika_consumer.py
  python/flask-pika/app/processmon.toml
  python/flask-pika/app/requirements.txt
  python/flask-pika/commands/run
  python/flask-pika/docker-compose.yml
Labels: enhancement, feature
