Repository appsignal/test-setups, pull requests merged in 2024-01, with the labels that each got.

#179 Clean up Elixir integration before build
  elixir/alpine-release/app/assets/package-lock.json
  elixir/alpine-release/app/mix.lock
  elixir/alpine-release/commands/prepare
  elixir/phoenix-example/commands/run
  elixir/plug-oban/commands/run
  elixir/plug/commands/run
  elixir/single-task/commands/run
Labels: dev happiness

#178 Update Python app AppSignal config location
  python/django4-celery/app/__appsignal__.py
  python/django4-celery/docker-compose.yml
  python/fastapi/app/__appsignal__.py
  python/fastapi/docker-compose.yml
  python/flask/app/__appsignal__.py
  python/flask/docker-compose.yml
  python/starlette/app/__appsignal__.py
  python/starlette/docker-compose.yml
Labels: chore

#180 Update Alpine Linux build dependencies
  elixir/alpine-release/Dockerfile
  ruby/sinatra-alpine/Dockerfile
Labels: dev happiness

#181 Add app demo command
  Rakefile
  nodejs/express-redis/commands/demo
Labels: dev happiness

#183 Add Redis to Sinatra test setup
  .semaphore/semaphore.yml
  ruby/sinatra-redis/Dockerfile
  ruby/sinatra-redis/app/Gemfile
  ruby/sinatra-redis/app/Gemfile.lock
  ruby/sinatra-redis/app/app.rb
  ruby/sinatra-redis/app/config.ru
  ruby/sinatra-redis/app/config/appsignal.yml
  ruby/sinatra-redis/app/processmon.toml
  ruby/sinatra-redis/commands/diagnose
  ruby/sinatra-redis/commands/run
  ruby/sinatra-redis/docker-compose.yml
Labels: chore

#184 Add Plug + Ecto test setup
  elixir/plug-ecto/Dockerfile
  elixir/plug-ecto/README.md
  elixir/plug-ecto/app/.formatter.exs
  elixir/plug-ecto/app/.gitignore
  elixir/plug-ecto/app/config/config.exs
  elixir/plug-ecto/app/lib/friends/actor.ex
  elixir/plug-ecto/app/lib/friends/character.ex
  elixir/plug-ecto/app/lib/friends/movie.ex
  elixir/plug-ecto/app/lib/friends/repo.ex
  elixir/plug-ecto/app/lib/plug_example.ex
  elixir/plug-ecto/app/lib/plug_example/application.ex
  elixir/plug-ecto/app/mix.exs
  elixir/plug-ecto/app/mix.lock
  elixir/plug-ecto/app/priv/repo/migrations/20240110163659_create_movies.exs
  elixir/plug-ecto/app/priv/repo/migrations/20240110163736_create_characters.exs
  elixir/plug-ecto/app/priv/repo/migrations/20240110164009_create_actors.exs
  elixir/plug-ecto/app/priv/repo/migrations/20240110164028_create_movies_actors.exs
  elixir/plug-ecto/app/priv/repo/migrations/20240122152703_add_example_data.exs
  elixir/plug-ecto/app/test/plug_example_test.exs
  elixir/plug-ecto/app/test/test_helper.exs
  elixir/plug-ecto/commands/diagnose
  elixir/plug-ecto/commands/run
  elixir/plug-ecto/docker-compose.yml
  elixir/plug-ecto/postgres.env
  elixir/plug/app/README.md
Labels: enhancement
